# Qwen3 0.6B Unmodified Model Baseline

Evaluates the base `Qwen/Qwen3-0.6B` model without LoRA/adapters as a zero-shot spam classifier. This is method `00`: the baseline before any fine-tuning.

The script can test both ways of extracting a class from the unmodified causal LM:

- generation + parsing
- next-token scoring between `ham` and `spam`

In [1]:
from pathlib import Path
import subprocess
import sys

def find_project_root(start: Path | None = None) -> Path:
    start = (start or Path.cwd()).resolve()
    for candidate in [start, *start.parents]:
        if (candidate / "dataset").is_dir() and (candidate / "lora-fine-tuning").is_dir():
            return candidate
    raise RuntimeError("Could not find project root.")

PROJECT_ROOT = find_project_root()
METHOD_DIR = PROJECT_ROOT / "lora-fine-tuning" / "methods" / "00_unmodified_model"
SCRIPT = METHOD_DIR / "qwen3_0.6b_unmodified_baseline.py"
RESULTS_ROOT = METHOD_DIR / "results"

RUN_ID = None
SAMPLE_COUNT = 100
MODE = "both"  # generation, next-token, or both
BATCH_SIZE = 2
MAX_SEQ_LENGTH = 1024

print(f"Project root: {PROJECT_ROOT}")
print(f"Script:       {SCRIPT}")
print(f"Results:      {RESULTS_ROOT}")

Project root: /Users/wojciechdrozdz/uni/Magisterka/Semestr III/Praca Magisterska
Script:       /Users/wojciechdrozdz/uni/Magisterka/Semestr III/Praca Magisterska/lora-fine-tuning/methods/00_unmodified_model/qwen3_0.6b_unmodified_baseline.py
Results:      /Users/wojciechdrozdz/uni/Magisterka/Semestr III/Praca Magisterska/lora-fine-tuning/methods/00_unmodified_model/results

In [2]:
command = [
    sys.executable,
    str(SCRIPT),
    "--results-root", str(RESULTS_ROOT),
    "--limit", str(SAMPLE_COUNT),
    "--mode", MODE,
    "--batch-size", str(BATCH_SIZE),
    "--max-seq-length", str(MAX_SEQ_LENGTH),
]
if RUN_ID:
    command.extend(["--run-id", RUN_ID])

print(" ".join(command))
subprocess.run(command, cwd=PROJECT_ROOT, check=True)

/Users/wojciechdrozdz/uni/Magisterka/Semestr III/Praca Magisterska/.venv/bin/python /Users/wojciechdrozdz/uni/Magisterka/Semestr III/Praca Magisterska/lora-fine-tuning/methods/00_unmodified_model/qwen3_0.6b_unmodified_baseline.py --results-root /Users/wojciechdrozdz/uni/Magisterka/Semestr III/Praca Magisterska/lora-fine-tuning/methods/00_unmodified_model/results --limit 100 --mode both --batch-size 2 --max-seq-length 1024
Combined dataset already exists: /Users/wojciechdrozdz/uni/Magisterka/Semestr III/Praca Magisterska/dataset/combined_datasets/generated/ceas_2008__trec_2007__dedupe_high__spam_0_5__0b6c8e960e.parquet

Filtering empty emails: 100%|██████████| 4061/4061 [00:00<00:00, 125864.14 examples/s]
Formatting prompts to <= 1024 tokens: 100%|██████████| 100/100 [00:00<00:00, 584.57 examples/s]

Using device: mps; dtype: torch.float16
Run ID: qwen3_0p6b_unmodified_20260509_185123
Samples: 100

Loading weights: 100%|██████████| 311/311 [00:02<00:00, 145.65it/s]
The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

{
  "generation_parsing": {
    "accuracy": 0.45,
    "balanced_accuracy": 0.5,
    "classification_failure_count": 0.0,
    "classification_failure_rate": 0.0,
    "f1": 0.0,
    "false_negative_count": 55.0,
    "false_positive_count": 0.0,
    "parse_failure_count": 0.0,
    "parse_failure_rate": 0.0,
    "precision": 0.0,
    "recall": 0.0,
    "specificity": 1.0,
    "true_negative_count": 45.0,
    "true_positive_count": 0.0
  },
  "next_token": {
    "accuracy": 0.45,
    "balanced_accuracy": 0.5,
    "classification_failure_count": 0.0,
    "classification_failure_rate": 0.0,
    "cross_entropy": 2.753732542736037,
    "f1": 0.0,
    "false_negative_count": 55.0,
    "false_positive_count": 0.0,
    "ham_f1": 0.6206896551724138,
    "ham_precision": 0.45,
    "ham_recall": 1.0,
    "macro_f1": 0.3103448275862069,
    "macro_precision": 0.225,
    "macro_recall": 0.5,
    "matthews_corrcoef": 0.0,
    "pr_auc": 0.4494908289568212,
    "precision": 0.0,
    "recall": 0.0,
    "roc_auc": 0.32343434343434346,
    "specificity": 1.0,
    "true_negative_count": 45.0,
    "true_positive_count": 0.0
  }
}
Wrote: /Users/wojciechdrozdz/uni/Magisterka/Semestr III/Praca Magisterska/lora-fine-tuning/methods/00_unmodified_model/results/runs/qwen3_0p6b_unmodified_20260509_185123/metrics.json
Wrote: /Users/wojciechdrozdz/uni/Magisterka/Semestr III/Praca Magisterska/lora-fine-tuning/methods/00_unmodified_model/results/runs/qwen3_0p6b_unmodified_20260509_185123/predictions.csv

CompletedProcess(args=['/Users/wojciechdrozdz/uni/Magisterka/Semestr III/Praca Magisterska/.venv/bin/python', '/Users/wojciechdrozdz/uni/Magisterka/Semestr III/Praca Magisterska/lora-fine-tuning/methods/00_unmodified_model/qwen3_0.6b_unmodified_baseline.py', '--results-root', '/Users/wojciechdrozdz/uni/Magisterka/Semestr III/Praca Magisterska/lora-fine-tuning/methods/00_unmodified_model/results', '--limit', '100', '--mode', 'both', '--batch-size', '2', '--max-seq-length', '1024'], returncode=0)

In [3]:
import json
import pandas as pd

run_dirs = sorted((RESULTS_ROOT / "runs").glob("qwen3_0p6b_unmodified_*"))
if not run_dirs:
    raise FileNotFoundError(f"No baseline runs found under {RESULTS_ROOT / 'runs'}")
latest_run_dir = run_dirs[-1]

with (latest_run_dir / "metrics.json").open("r", encoding="utf-8") as f:
    metrics = json.load(f)
predictions = pd.read_csv(latest_run_dir / "predictions.csv")

print(latest_run_dir)
display(pd.DataFrame(metrics["metrics"]).T)
display(predictions.head(30))

/Users/wojciechdrozdz/uni/Magisterka/Semestr III/Praca Magisterska/lora-fine-tuning/methods/00_unmodified_model/results/runs/qwen3_0p6b_unmodified_20260509_185123

,accuracy,balanced_accuracy,classification_failure_count,classification_failure_rate,f1,false_negative_count,false_positive_count,parse_failure_count,parse_failure_rate,precision,...,cross_entropy,ham_f1,ham_precision,ham_recall,macro_f1,macro_precision,macro_recall,matthews_corrcoef,pr_auc,roc_auc
generation_parsing,0.45,0.5,0.0,0.0,0.0,55.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
next_token,0.45,0.5,0.0,0.0,0.0,55.0,0.0,NaN,NaN,0.0,...,2.753733,0.62069,0.45,1.0,0.310345,0.225,0.5,0.0,0.449491,0.323434

,actual,correct,method,p_ham,p_spam,parse_failed,predicted,raw_generation,sample_index,subject,token_length,was_trimmed
0,ham,True,generation_parsing,NaN,NaN,False,ham,ham<|im_end|>,0,RE: crazy TV laws,264,False
1,ham,True,generation_parsing,NaN,NaN,False,ham,ham<|im_end|>,1,Trade Me -- New Feedback Posted. Auction: 1292...,186,False
2,spam,False,generation_parsing,NaN,NaN,False,ham,ham<|im_end|>,2,Premium Health Coverage for less than 3 bucks ...,354,False
3,spam,False,generation_parsing,NaN,NaN,False,ham,ham<|im_end|>,3,For Customer,469,False
4,spam,False,generation_parsing,NaN,NaN,False,ham,ham<|im_end|>,4,CNN Alerts: My Custom Alert,195,False
5,ham,True,generation_parsing,NaN,NaN,False,ham,ham<|im_end|>,5,Re: [R] Change the mode of a list,469,False
6,spam,False,generation_parsing,NaN,NaN,False,ham,ham<|im_end|>,6,Internet Explorer 7,209,False
7,ham,True,generation_parsing,NaN,NaN,False,ham,ham<|im_end|>,7,[R] GLMM for unbalanced data,424,False
8,spam,False,generation_parsing,NaN,NaN,False,ham,ham<|im_end|>,8,You can not miss this opportunity on Spring,347,False
9,ham,True,generation_parsing,NaN,NaN,False,ham,ham<|im_end|>,9,Re: [Python-Dev] unscriptable?,349,False
10,spam,False,generation_parsing,NaN,NaN,False,ham,ham<|im_end|>,10,My notebook none mohammedan,119,False
11,spam,False,generation_parsing,NaN,NaN,False,ham,ham<|im_end|>,11,hi from ashly,100,False
12,ham,True,generation_parsing,NaN,NaN,False,ham,ham<|im_end|>,12,RE: [opensuse] Apache and SSL,152,False
13,spam,False,generation_parsing,NaN,NaN,False,ham,ham<|im_end|>,13,lehigh soothsayer towel commissary exempt,180,False
14,ham,True,generation_parsing,NaN,NaN,False,ham,ham<|im_end|>,14,Re: [Python-Dev] NeedsReview keyword,290,False
15,spam,False,generation_parsing,NaN,NaN,False,ham,ham<|im_end|>,15,Fw: Do you want a {}prosperous fuutre?,412,False
16,spam,False,generation_parsing,NaN,NaN,False,ham,ham<|im_end|>,16,New security level,67,False
17,ham,True,generation_parsing,NaN,NaN,False,ham,ham<|im_end|>,17,1130p 6/15 Update: NASA elated with computer r...,1024,True
18,spam,False,generation_parsing,NaN,NaN,False,ham,ham<|im_end|>,18,High-feature medication for you.,69,False
19,spam,False,generation_parsing,NaN,NaN,False,ham,ham<|im_end|>,19,We are ready to give you a loan,70,False
20,ham,True,generation_parsing,NaN,NaN,False,ham,ham<|im_end|>,20,Re: [cc-community] Does BY-SA extend to a news...,1003,False
21,ham,True,generation_parsing,NaN,NaN,False,ham,ham<|im_end|>,21,Re: [R] Problem installing Rmpi with lam on SG...,496,False
22,spam,False,generation_parsing,NaN,NaN,False,ham,ham<|im_end|>,22,It will also construct a JNotepad class hierar...,585,False
23,ham,True,generation_parsing,NaN,NaN,False,ham,ham<|im_end|>,23,[UAI] 2nd CFP: Artificial Societies for Ambien...,351,False
24,spam,False,generation_parsing,NaN,NaN,False,ham,ham<|im_end|>,24,Gain up to 4 extra inches,122,False
25,spam,False,generation_parsing,NaN,NaN,False,ham,ham<|im_end|>,25,We hope this information will help you to make...,161,False
26,ham,True,generation_parsing,NaN,NaN,False,ham,ham<|im_end|>,26,IO::Pipe::End DESTROY ? Shouldn't close() be c...,215,False
27,ham,True,generation_parsing,NaN,NaN,False,ham,ham<|im_end|>,27,Re: [Python-3000] Displaying strings containin...,282,False
28,spam,False,generation_parsing,NaN,NaN,False,ham,ham<|im_end|>,28,"SPECIAL PHARMACY DISCOUNT, you pay & we ship,...",687,False
29,ham,True,generation_parsing,NaN,NaN,False,ham,ham<|im_end|>,29,[perl #41569] [BUG] t/distro/file_metadata.t f...,110,False

In [4]:
for method, group in predictions.groupby("method"):
    print("=" * 80)
    print(method)
    correct = int(group["correct"].sum())
    total = len(group)
    print(f"Correct: {correct}/{total} ({correct / max(total, 1):.2%})")
    display(pd.crosstab(group["actual"], group["predicted"], rownames=["actual"], colnames=["predicted"], dropna=False))
    if "parse_failed" in group:
        print(f"Parse failures: {int(group['parse_failed'].sum())}/{total}")
    display(group.loc[~group["correct"]].head(20))

================================================================================
generation_parsing
Correct: 45/100 (45.00%)

predicted  ham
actual
ham         45
spam        55

Parse failures: 0/100

,actual,correct,method,p_ham,p_spam,parse_failed,predicted,raw_generation,sample_index,subject,token_length,was_trimmed
2,spam,False,generation_parsing,NaN,NaN,False,ham,ham<|im_end|>,2,Premium Health Coverage for less than 3 bucks ...,354,False
3,spam,False,generation_parsing,NaN,NaN,False,ham,ham<|im_end|>,3,For Customer,469,False
4,spam,False,generation_parsing,NaN,NaN,False,ham,ham<|im_end|>,4,CNN Alerts: My Custom Alert,195,False
6,spam,False,generation_parsing,NaN,NaN,False,ham,ham<|im_end|>,6,Internet Explorer 7,209,False
8,spam,False,generation_parsing,NaN,NaN,False,ham,ham<|im_end|>,8,You can not miss this opportunity on Spring,347,False
10,spam,False,generation_parsing,NaN,NaN,False,ham,ham<|im_end|>,10,My notebook none mohammedan,119,False
11,spam,False,generation_parsing,NaN,NaN,False,ham,ham<|im_end|>,11,hi from ashly,100,False
13,spam,False,generation_parsing,NaN,NaN,False,ham,ham<|im_end|>,13,lehigh soothsayer towel commissary exempt,180,False
15,spam,False,generation_parsing,NaN,NaN,False,ham,ham<|im_end|>,15,Fw: Do you want a {}prosperous fuutre?,412,False
16,spam,False,generation_parsing,NaN,NaN,False,ham,ham<|im_end|>,16,New security level,67,False
18,spam,False,generation_parsing,NaN,NaN,False,ham,ham<|im_end|>,18,High-feature medication for you.,69,False
19,spam,False,generation_parsing,NaN,NaN,False,ham,ham<|im_end|>,19,We are ready to give you a loan,70,False
22,spam,False,generation_parsing,NaN,NaN,False,ham,ham<|im_end|>,22,It will also construct a JNotepad class hierar...,585,False
24,spam,False,generation_parsing,NaN,NaN,False,ham,ham<|im_end|>,24,Gain up to 4 extra inches,122,False
25,spam,False,generation_parsing,NaN,NaN,False,ham,ham<|im_end|>,25,We hope this information will help you to make...,161,False
28,spam,False,generation_parsing,NaN,NaN,False,ham,ham<|im_end|>,28,"SPECIAL PHARMACY DISCOUNT, you pay & we ship,...",687,False
32,spam,False,generation_parsing,NaN,NaN,False,ham,ham<|im_end|>,32,Don't blame us for not telling you about this ...,268,False
36,spam,False,generation_parsing,NaN,NaN,False,ham,ham<|im_end|>,36,For Ktwarwic,224,False
37,spam,False,generation_parsing,NaN,NaN,False,ham,ham<|im_end|>,37,From Winnie Sharpe,90,False
38,spam,False,generation_parsing,NaN,NaN,False,ham,ham<|im_end|>,38,XanaViagra\\/aliunCialisPhentemine from $;2.00...,701,False

================================================================================
next_token
Correct: 45/100 (45.00%)

predicted  ham
actual
ham         45
spam        55

Parse failures: 0/100

,actual,correct,method,p_ham,p_spam,parse_failed,predicted,raw_generation,sample_index,subject,token_length,was_trimmed
102,spam,False,next_token,0.988770,0.011330,False,ham,NaN,2,Premium Health Coverage for less than 3 bucks ...,354,False
103,spam,False,next_token,0.988281,0.011871,False,ham,NaN,3,For Customer,469,False
104,spam,False,next_token,0.994141,0.005821,False,ham,NaN,4,CNN Alerts: My Custom Alert,195,False
106,spam,False,next_token,0.986816,0.013023,False,ham,NaN,6,Internet Explorer 7,209,False
108,spam,False,next_token,0.993652,0.006191,False,ham,NaN,8,You can not miss this opportunity on Spring,347,False
110,spam,False,next_token,0.995117,0.004681,False,ham,NaN,10,My notebook none mohammedan,119,False
111,spam,False,next_token,0.997070,0.003172,False,ham,NaN,11,hi from ashly,100,False
113,spam,False,next_token,0.993164,0.006905,False,ham,NaN,13,lehigh soothsayer towel commissary exempt,180,False
115,spam,False,next_token,0.995605,0.004265,False,ham,NaN,15,Fw: Do you want a {}prosperous fuutre?,412,False
116,spam,False,next_token,0.994629,0.005138,False,ham,NaN,16,New security level,67,False
118,spam,False,next_token,0.995117,0.004982,False,ham,NaN,18,High-feature medication for you.,69,False
119,spam,False,next_token,0.994629,0.005554,False,ham,NaN,19,We are ready to give you a loan,70,False
122,spam,False,next_token,0.992188,0.007935,False,ham,NaN,22,It will also construct a JNotepad class hierar...,585,False
124,spam,False,next_token,0.995605,0.004467,False,ham,NaN,24,Gain up to 4 extra inches,122,False
125,spam,False,next_token,0.994141,0.006096,False,ham,NaN,25,We hope this information will help you to make...,161,False
128,spam,False,next_token,0.998535,0.001623,False,ham,NaN,28,"SPECIAL PHARMACY DISCOUNT, you pay & we ship,...",687,False
132,spam,False,next_token,0.977051,0.022980,False,ham,NaN,32,Don't blame us for not telling you about this ...,268,False
136,spam,False,next_token,0.986328,0.013428,False,ham,NaN,36,For Ktwarwic,224,False
137,spam,False,next_token,0.997559,0.002632,False,ham,NaN,37,From Winnie Sharpe,90,False
138,spam,False,next_token,0.998047,0.002115,False,ham,NaN,38,XanaViagra\\/aliunCialisPhentemine from $;2.00...,701,False